services:
  fraction-game:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3721:80"

  bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    restart: unless-stopped
    environment:
      - BOT_TOKEN=8339359469:AAFbPscEVLGtvCsAruuP--ws3fK89bvf1SQ
